[workspace]
authors = ["allennnnnz <allenzhuang0117@gmail.com>"]
channels = ["conda-forge"]
name = "HW3"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
bison = ">=3.8.2,<4"
flex = ">=2.6.4,<3"
make = ">=4.4.1,<5"
